# Generated by Django 5.2.8 on 2025-11-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='responsable_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='responsable_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
